name: 'Fitzgerald Advisors, LLC'
favicon: null
layout_spectrum: 0.65693
typography_spectrum: 0.43478
title: 'Fitzgerald Advisors, LLC | Loan Sales '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0708'
    - '#2b2024'
    - '#5f64b5'
    - '#98abe3'
    - '#bde7fd'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
